services:
  backend:
    image: led-act-backend:latest
    container_name: led_act_backend
    restart: unless-stopped
    # PASSO PRINCIPAL
    devices:
      - /sys/class/leds:/sys/class/leds
    privileged: true

    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    container_name: led_act_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
    # Mapeia a pasta fronted para o diretório padrão do Nginx
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend